### PR TITLE
Add Rishikesh

### PR DESCRIPTION
**Pull request by rishikesh7355**

### CODE REVIEW

**Review by akshitagupta15june — APPROVED** [review]

**Review by akshitagupta15june — APPROVED** [review]

**Comment by rishikesh7355** [comment]
Thanks Akshita

**Comment by rishikesh7355** [comment]
Hello Ma'am ;
Could you help me to contribute to a project having at least 100 stars as I
am a beginner and it might help me to get a Microsoft internship before 31
August. I need to submit the assignment.
Thank You

**Comment by akshitagupta15june** [comment]
Yes you can contribute

**Comment by rishikesh7355** [comment]
How to start and search for beginner friendly project having 100 stars ?

**Pull request closed without merging**
